FROM golang:latest AS build
WORKDIR /build
COPY go.mod ./
COPY cmd/addrd ./
COPY internal ./internal/
RUN go mod tidy
RUN go build -v -o addrd

FROM debian:trixie-slim
RUN apt-get update
RUN apt-get install -y ca-certificates
COPY --from=build /build/addrd /usr/bin/
ENTRYPOINT ["/usr/bin/addrd"]
